# Generated by Django 4.2 on 2023-10-26 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('video', models.FileField(null=True, upload_to='Videos/')),
                ('file_type', models.CharField(blank=True, max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Video Files Records',
                'ordering': ['name', 'created'],
            },
        ),
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('speaker', models.CharField(db_column='voice', max_length=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chat Bot Records',
                'ordering': ['name', 'speaker'],
            },
        ),
        migrations.CreateModel(
            name='AudioFiles',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('audio', models.FileField(null=True, upload_to='Audios/')),
                ('accent', models.CharField(blank=True, max_length=20)),
                ('file_type', models.CharField(blank=True, max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audio Files Records',
                'ordering': ['name', 'created'],
            },
        ),
    ]
